"""create student_feedback table

Revision ID: 4097ab38c805
Revises: 
Create Date: 2026-04-18 11:31:26.945892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4097ab38c805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('study_hours_per_day', sa.Integer(), nullable=False),
    sa.Column('attendance_percentage', sa.Integer(), nullable=False),
    sa.Column('active_backlogs', sa.Integer(), nullable=False),
    sa.Column('academic_feedback', sa.String(length=20), nullable=False),
    sa.Column('emotional_feedback', sa.String(length=20), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_feedback_id'), 'student_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_student_feedback_roll_number'), 'student_feedback', ['roll_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_feedback_roll_number'), table_name='student_feedback')
    op.drop_index(op.f('ix_student_feedback_id'), table_name='student_feedback')
    op.drop_table('student_feedback')
    # ### end Alembic commands ###
